language: java
jdk:
  - oraclejdk11
script: mvn clean verify
cache:
  directories:
    - $HOME/.m2
deploy:
   provider: script
   script: .travis/release.sh
   skip_cleanup: true
   on:
    repo: teste
    tags: true
    jdk: oraclejdk11
